name = "calendar"
main = "src/worker.js"
compatibility_date = "2024-11-11"
workers_dev = false
preview_urls = false

[[routes]]
pattern = "workers.tablerus.es/calendar/*"
zone_name = "tablerus.es"

[placement]
mode = "smart"

[observability]
enabled = false

  [observability.logs]
  enabled = true
  head_sampling_rate = 1
  invocation_logs = true

[[kv_namespaces]]
id = "517a67ba80cc4502a95f28788570251f"
binding = "CALENDAR_DATA"
